### ISSUE TITLE
Add "bacdive" topic to repo

### ISSUE THREAD

**Issue by katrinleinweber** [EngqvistLab/fetch_microbial_growth_temperatures#1]
Thanks for publishing your code :-) There is already a small group assembled under [GitHub.com/topics/bacdive](https://github.com/topics/bacdive), with https://github.com/zorino/microbe-dbs/issues/2 & https://github.com/cameronmartino/BacDive_/issues/2 also invited.

It would be great if you helped curate that list by adding `bacdive` as a topic to your repo as well. Cheers!

**Comment by mengqvist** [comment]
No problem, I'm happy to share. As you suggested, I have added the bacdive topic.

**Comment by katrinleinweber** [comment]
Cool :-)
